### ISSUE TITLE
Nesting does not work

### ISSUE THREAD

**Issue by erikscheepers** [calebporzio/project-x#7]
Looks very nice. Tried it immediately in the navigation section of my project. Works great already! But unfortunately I stumbled on some issues when trying to make a nested dropdown menu.

```html
<div x-data="{ open: false }">
    <button x-on:click="open = true">Open Dropdown</button>

    <ul
        class="hidden"
        x-bind:class="{ 'hidden': ! open }"
        x-on:click.away="open = false"
    >
        Dropdown Body
        <div x-data="{ another: false }">
            <button x-on:click="another = true">Open another Dropdown</button>

            <ul
                class="hidden"
                x-bind:class="{ 'hidden': ! another }"
                x-on:click.away="another = false"
            >
                Another dropdown Body
            </ul>
        </div>
    </ul>
</div>
````
Opening the first dropdown works, but opening the second fails because of the error:
> ReferenceError: another is not defined

**Comment by erikscheepers** [comment]
Fixed it by defining all variables on top.
```html
<div x-data="{ open: false, another: false }">
    <button x-on:click="open = true">Open Dropdown</button>

    <ul
        class="hidden"
        x-bind:class="{ 'hidden': ! open }"
        x-on:click.away="open = false"
    >
        Dropdown Body
        <div>
            <button x-on:click="another = true">Open another Dropdown</button>

            <ul
                class="hidden"
                x-bind:class="{ 'hidden': ! another }"
                x-on:click.away="another = false"
            >
                Another dropdown Body
            </ul>
        </div>
    </ul>
</div>
```

**Comment by tlgreg** [comment]
Tbf that doesn't really fix nesting, you jus avoided nesting. :)
Should nesting be even a feature though?

**Comment by erikscheepers** [comment]
In my mind I can justify my fix/solution: declare all variables in the top. I haven't encountered a situation yet where "real" nesting should be supported. For now this is OK.

**Comment by erikscheepers** [comment]
In version [v0.3.0](https://github.com/calebporzio/project-x/tree/v0.3.0) the nesting of components has been added ([commit](https://github.com/calebporzio/project-x/commit/747673a91562a88ca32967c03c0d46f30e87baee)).
Thanks @calebporzio, makes my code more clean and easier to maintain.

**Comment by calebporzio** [comment]
Awesome!
